Cu 014 mb novedades
ITR-MALBRAN-ORT/ForoRenacMobile pull request #3
Opened 2022-11-11 12:48 UTC by LopezElFacha

2022-11-17 12:33 UTC, JuliaVallejos requested changes
Recordá ponerme como reviewer en el Pull Request para que me lleguen los mails cuando subis algo

2022-11-17 12:33 UTC, JuliaVallejos commented on ForoRenac/app/ui/screens/NewsScreen/NewsUI.jsx
> +      <FlatList data={Data} horizontal renderItem={NewsCard} style={{padding: 20}} />
Al ser una app mobile por un tema de experiencia de usuario normalmente renderizamos las Flatlist en vertical. 
Podes usar un ItemSeparatorComponent de una View de por ejemplo 10 px de altura; para separar las cards

2022-11-18 12:50 UTC, LopezJuanIgnacio commented on ForoRenac/app/ui/screens/NewsScreen/NewsUI.jsx
> +      <FlatList data={Data} horizontal renderItem={NewsCard} style={{padding: 20}} />
ahi estaria

2022-11-23 13:48 UTC, JuliaVallejos approved these changes

2022-11-23 13:50 UTC, merged